import React from "react";
import styles from "./Documentcategories.module.css";
import Clipath from "../../../assets/Clipath.png";


export default function Documentcategories() {
  return (
    <div>
      <div className={styles.tableContainer}>
        <table className={styles.table}>
          <thead>
            <tr>
              <th style={{ width: 36 }}></th>
              <th>Document Name</th>
              <th>Generated For</th>
              <th> Document Category</th>
              <th> Generated By</th>
              <th>Generated On</th>
              <th style={{ width: 96 }}>Actions</th>
            </tr>
          </thead>
        </table>
        <div className={styles.imagediv}>
          <img src={Clipath} />
          <p>There are no records to display</p>
        </div>
      </div>
    </div>
  );
}
